name: Delete Old Branches

on:
  workflow_dispatch:

jobs:
  delete_old_branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch all branches
      run: git fetch --prune --tags

    - name: Calculate one month ago date
      id: calculate_date
      run: |
        current_date=$(date -u "+%s")
        one_month_ago_date=$(date -d "-1 month" "+%s" 2>/dev/null || date -j -v -1m "+%s" 2>/dev/null)
        echo "Calculated one month ago date: $(date -d @$one_month_ago_date "+%Y-%m-%d")"
        echo "ONE_MONTH_AGO_DATE=$one_month_ago_date" >> $GITHUB_ENV
    
    - name: List branches for debugging
      run: |
        git branch -r
        echo "Threshold date: $(date -d @$one_month_ago_date "+%Y-%m-%d")"

    - name: Run delete branches script
      run: |
        threshold_date=${ONE_MONTH_AGO_DATE}
        
        # Loop through all remote branches
        for branch in $(git branch -r | grep -v HEAD | sed 's/origin\///'); do
            if [ "$branch" != "development" ] && [ "$branch" != "master" ] && [ "$branch" != "main" ] && [ "$branch" != "production" ] && [ "$branch" != "staging" ]; then
                branch_commit_date=$(git log -1 --format="%ci" --branches=origin/$branch)
                if [ "$branch_commit_date" \< "$threshold_date" ]; then
                    echo "Branch to delete: $branch"
                    # Uncomment the next line to delete the branches
                    # git push origin --delete $branch
                else
                    echo "Branch created after threshold date: $branch"
                fi
            fi
        done
