name: Delete Old Branches

on:
  workflow_dispatch:

jobs:
  delete_old_branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq -y

    - name: Fetch all branches
      run: git fetch --prune --tags

    - name: Calculate one month ago date
      id: calculate_date
      run: |
        current_date=$(date -u "+%Y-%m-%d")
        one_month_ago_date=$(date -d "-1 month" "+%Y-%m-%d" 2>/dev/null || date -j -v -1m "+%Y-%m-%d" 2>/dev/null)
        echo "Calculated one month ago date: $one_month_ago_date"
        echo "ONE_MONTH_AGO_DATE=$one_month_ago_date" >> $GITHUB_ENV
    
    - name: List branches for debugging
      run: |
        git branch -r
        echo "Threshold date: $(date -d @$one_month_ago_date "+%Y-%m-%d")"

    - name: List branches with last commit date
      id: list_branches
      run: |
        branches=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/branches" | jq -r '.[] | select(.name != "main" and .name != "master" and .commit.committer.date < "'"$one_month_ago_date"'") | .name')
        echo "Branches to delete: $branches"
    
    - name: Run delete branches script
      run: |
        for branch in $branches; do
            echo "Deleting branch: $branch"
            git push origin --delete $branch
        done
