name: Delete Old Branches

on:
  schedule:
    - cron: '18 10 * * *' # Runs every day at 10:10 AM
 # Runs every day at midnight (adjust as needed)

jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --prune --tags

      - name: List branches and timestamps
        run: git for-each-ref --sort=committerdate --format="%(committerdate:short) %(refname:short)" refs/heads/* | grep -vE "refs/heads/(master|main|development|staging|production)" > branches.txt

      - name: Delete old branches
        run: |
          today=$(date -u +"%Y-%m-%d")
          thirty_days_ago=$(date -u -d "$today -30 days" +"%Y-%m-%d")
          while read -r branch_date branch_name; do
            if [[ $branch_date < $thirty_days_ago ]]; then
              echo "Deleting branch $branch_name"
              git push origin --delete "$branch_name"
            else
              echo "Branch $branch_name is not old enough to delete"
            fi
          done < branches.txt
